services:
  - type: web
    name: cyrus
    env: node
    buildCommand: npm install --legacy-peer-deps && pip install -r requirements.txt && npm run build
    startCommand: npm run start:all
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3200
      - key: CYRUS_AI_PORT
        value: 8001
